version: "3"
services:
    sonarqube:
        container_name: "sonar-v10.5.1"
        image: sonarqube:10.5.1
        build: 
            dockerfile: Dockerfile.sonarqube
        ports:
          - 9000:9000
        depends_on:
            - db
        environment:
            SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonartest
            SONAR_JDBC_USERNAME: sonartest
            SONAR_JDBC_PASSWORD: sonartest
        volumes:
            - ./sonar/data:/opt/sonarqube/data
            - ./sonar/extensions:/opt/sonarqube/extensions
            - ./sonar/logs:/opt/sonarqube/logs
        ulimits:
            nofile:
              soft: 262144
              hard: 262144
    db:
        container_name: "postgres-sonar-v15"
        image: postgres-sonar:15
        build:
            dockerfile: Dockerfile.postgres
        environment:
            POSTGRES_USER: sonartest
            POSTGRES_PASSWORD: sonartest
        ports:
            - 5432:5432
        volumes:
            - ./postgresql:/var/lib/postgresql
            - ./postgresql/data:/var/lib/postgresql/data    
networks:
  default:
    external: 
      name: devopsnet
