FROM sonarqube:10.5.1-community

# if we want to install
USER root

# Update the package list, install sudo, create a non-root user, and grant password-less sudo permissions
RUN apt update && \
    apt install -y sudo && \
	apt install -y curl
	
RUN echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' > /etc/nsswitch.conf

# drop back to the regular sonarqube user - good practice
USER sonarqube